config/routes.rb
Rails.application.routes.draw do
  root "users#new"
  resources :users
  resources :cities, only: [:index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  has_many :users, dependent: :destroy
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :states
end

app/models/gender.rb
class Gender < ApplicationRecord
  has_many :users
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :cities, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :gender
  belongs_to :city, counter_cache: true
  belongs_to :country
  belongs_to :state

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name, :last_name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :birth_date, presence: true
  validates :address, presence: true
  validates :house_or_apartment, presence: true
  validates :city_id, presence: true
  validates :country_id, presence: true
  validates :state_id, presence: true
  validates :gender_id, presence: true
  validate :must_be_over_18
  validate :maximum_three_users_per_city, on: :create, unless: -> { city.nil? }

  def must_be_over_18
    if birth_date.present? && birth_date > 18.years.ago.to_date
      errors.add(:birth_date, 'Debes ser mayor de 18 años')
    end
  end

  def maximum_three_users_per_city
    if city.users_count >= 3
      errors.add(:city, 'La ciudad ya tiene 3 usuarios registrados')
    end
  end

  private
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.joins(:users).select('cities.*, COUNT(users.id) as user_count').group('cities.id')

    respond_to do |format|
      format.html
      format.json { render json: @cities }
      format.pdf do
        render pdf: "file_name", template: "cities/index", formats: [:html], layout: "pdf", orientation: 'Landscape'
      end
    end
  end

  def show
    @city = City.includes(users: [{city: [{state: :country}]}, :gender]).find(params[:id])

    respond_to do |format|
      format.html
      format.json
      format.pdf do
        render pdf: "Users in #{@city_name}", template: "cities/city", formats: [:html], layout: "pdf", orientation: 'Landscape'
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.includes(:gender, city: { state: :country })

    respond_to do |format|
      format.html
      format.json { render json: @users }
      format.pdf do
        render pdf: "file_name", template: "users/users", formats: [:html], layout: "pdf", orientation: 'Landscape'
      end
    end
  end

  # GET /users/1 or /users/1.json
  def show
    user = User.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @user }
      format.pdf do
        render pdf: "#{user.first_name} information", template: "users/user", formats: [:html], layout: "pdf", orientation: 'Landscape'
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to cities_url, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to city_url(City.find(@user.city_id)), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      flash[:notice] = "User was successfully destroyed."
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :birth_date, :email, :address, :house_or_apartment, :gender_id, :city_id, :country_id, :state_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/city.html.erb
<h1>Usuarios en <%= @city.name %></h1>

<p>
  PDF generated
  <%= Time.zone.now %>
</p>

<table class="user-info-table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Birth date</th>
      <th>Email</th>
      <th>Address</th>
      <th>House or Apartment</th>
      <th>Gender</th>
      <th>City</th>
      <th>Country</th>
      <th>State</th>
    </tr>
  </thead>
  <tbody>
  <% @city.users.each do |user| %>
    <%= render 'users/user_pdf', user: user %>
  <% end %>
  </tbody>
</table>

app/views/cities/index.html.erb
<!-- app/views/cities/index.html.erb -->
<h1 class="page-title">Ciudades</h1>

<table class="user-info-table">
  <thead>
    <tr>
      <th>Ciudad</th>
      <th>Número de Usuarios</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= link_to city.name, city %></td>
        <td><%= city.user_count %></td>
        <td>
          <%= link_to "PDF", city_path(city, format: :pdf)%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "see all users", users_path, class: "btn btn-primary new-user"  %>

<%= link_to "Back", 'javascript:history.back()', class: "back-btn" %>

app/views/cities/show.html.erb
<h1>Usuarios en <%= @city.name %></h1>

<table class="user-info-table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Birth date</th>
      <th>Email</th>
      <th>Address</th>
      <th>House or Apartment</th>
      <th>Gender</th>
      <th>City</th>
      <th>Country</th>
      <th>State</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @city.users.each do |user| %>
    <%= render 'users/user', user: user %>
  <% end %>
  </tbody>
</table>
</ul>

<%= link_to "Back", 'javascript:history.back()', class: "back-btn" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cincoventicinco</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <% if flash[:notice].present? %>
      <p style="color: green" class="notice"><%= flash[:notice] %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  <body onload='number_pages'>
    <div id="header">
      <%= wicked_pdf_image_tag 'mysite.jpg' %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav>
  <%= link_to "Form", :root, class: "nav-link" %>
  <%= link_to "Cities", cities_path, class: "nav-link"%>
</nav>

app/views/users/_form.html.erb
<%= form_with(model: user, html: { class: "add-user-form" }) do |form| %>
<h1 class="form-title"> CONTACTO </h1>
  <div class="form-group">
    <%= form.text_field :first_name, class: "form-control", placeholder: "Nombre*" %>
    <% if user.errors[:first_name].any? %>
      <div class="error-message">
        <%= user.errors[:first_name].first %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.text_field :last_name, class: "form-control", placeholder: "Apellido*" %>
    <% if user.errors[:last_name].any? %>
      <div class="error-message">
        <%= user.errors[:last_name].first %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.date_field :birth_date, class: "form-control",  id: "date_of_birth_select", placeholder: "Fecha de Nacimiento*" %>
    <% if user.errors[:birth_date].any? %>
      <div class="error-message">
        <%= user.errors[:birth_date].first %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.text_field :email, class: "form-control", placeholder: "Correo Electrónico*" %>
    <% if user.errors[:email].any? %>
      <div class="error-message">
        <%= user.errors[:email].first %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.collection_select :gender_id, Gender.order(:description), :id, :description, { include_blank: "Género*" }, { class: "form-control", id: "gender_select" } %>
    <% if user.errors[:gender_id].any? %>
      <div class="error-message">
        <%= user.errors[:gender_id].first %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.text_field :address, class: "form-control", placeholder: "Dirección*" %>
    <% if user.errors[:address].any? %>
      <div class="error-message">
        <%= user.errors[:address].first %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.text_field :house_or_apartment, class: "form-control", placeholder: "Casa o Apartamento*" %>
    <% if user.errors[:house_or_apartment].any? %>
      <div class="error-message">
        <%= user.errors[:house_or_apartment].first %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.collection_select :country_id, Country.order(:name), :id, :name, { include_blank: "País*" }, { class: "form-control", id: 'country_select' } %>
    <% if user.errors[:country_id].any? %>
      <div class="error-message">
        <%= user.errors[:country_id].first %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.collection_select :state_id, State.order(:name), :id, :name, { include_blank: "Estado/Provincia*" }, { class: "form-control", id: 'state_select' } %>
    <% if user.errors[:state_id].any? %>
      <div class="error-message">
        <%= user.errors[:state_id].first %>
      </div>
    <% end %>
  </div>

    <div class="form-group">
    <%= form.collection_select :city_id, City.order(:name), :id, :name, { include_blank: "Ciudad*" }, { class: "form-control", id: 'city_select'} %>
    <% if user.errors[:city].any? || user.errors[:city_id].any? %>
      <div class="error-message">
        <%= user.errors[:city].first %>
        <%= user.errors[:city_id].first %>
      </div>
    <% end %>
  </div>

  <div class="form-group btn-container">
    <%= form.submit "Registrar", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/users/_user.html.erb
<tr id="<%= dom_id(user) %>">
  <td><%= user.first_name %></td>
  <td><%= user.last_name %></td>
  <td><%= user.birth_date %></td>
  <td><%= user.email %></td>
  <td><%= user.address %></td>
  <td><%= user.house_or_apartment %></td>
  <td><%= user.gender.description %></td>
  <td><%= user.city.name %></td> 
  <td><%= user.city.state.country.name %></td>
  <td><%= user.city.state.name %></td>
  <td class="actions-container">
    <%= link_to "Edit", edit_user_path(user), class: 'edit-button' %> |
    <%= link_to "PDF", user_path(user, format: :pdf), class: 'pdf-button'%> |
    <%= button_to "X", user, method: :delete, class: 'delete-button', data: { confirm: '¿Estás seguro de que deseas eliminar este usuario?' } %>
  </td>
</tr>

app/views/users/_user_pdf.html.erb
<tr id="<%= dom_id(user) %>">
  <td><%= user.first_name %></td>
  <td><%= user.last_name %></td>
  <td><%= user.birth_date %></td>
  <td><%= user.email %></td>
  <td><%= user.address %></td>
  <td><%= user.house_or_apartment %></td>
  <td><%= user.gender.description %></td>
  <td><%= user.city.name %></td> 
  <td><%= user.city.state.country.name %></td> 
  <td><%= user.city.state.name %></td> 
</tr>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
 <%= link_to "Back", 'javascript:history.back()', class: "back-btn" %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<%= link_to "Crear PDF de usuarios", users_path(format: :pdf), class: "pdf-btn"%>

<table class="user-info-table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Nacimiento</th>
      <th>Email</th>
      <th>Dirección</th>
      <th>Casa/Apartamento</th>
      <th>Sexo</th>
      <th>Ciudad</th>
      <th>Pais</th>
      <th>Departamento</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <%= render user %>
    <% end %>
  </tbody>
</table>

<%= link_to "New user", new_user_path, class: "btn btn-primary new-user" %>

app/views/users/new.html.erb
<h1 class="contact-form-title">FORMULARIO DE CONTACTO</h1>

<div class="add-user-container">
  <div class="social-media-container">

  </div>
  <div class="user-form-container">
    <%= render "form", user: @user %>
  </div>
</div>

<br>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @user.first_name + ' ' + @user.last_name %></h1>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Nacimiento</th>
      <th>Email</th>
      <th>Dirección</th>
      <th>Casa/Apartamento</th>
      <th>Sexo</th>
      <th>Ciudad</th>
      <th>Pais</th>
      <th>Departamento</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tr>
    <%= render @user %>
  </tr>
</table>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back", 'javascript:history.back()' %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/users/user.html.erb
<h1><%= @user.first_name + ' ' + @user.last_name %></h1>
<p>
  PDF generated
  <%= Time.zone.now %>
</p>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Nacimiento</th>
      <th>Email</th>
      <th>Dirección</th>
      <th>Casa/Apartamento</th>
      <th>Sexo</th>
      <th>Ciudad</th>
      <th>Pais</th>
      <th>Departamento</th>
    </tr>
  </thead>
  <tr>
    <%= render 'user_pdf', user: @user %>
  </tr>
</table>

app/views/users/users.html.erb
<h1>Usuarios</h1>

<p>
  PDF generated
  <%= Time.zone.now %>
</p>

<table class="user-info-table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Nacimiento</th>
      <th>Email</th>
      <th>Dirección</th>
      <th>Casa/Apartamento</th>
      <th>Sexo</th>
      <th>Ciudad</th>
      <th>Pais</th>
      <th>Departamento</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <%= render 'user_pdf', user: user %>
    <% end %>
  </tbody>
</table>